ExampleConfig:
  base: null
  guidance_scale: 15
  init_image: null
  init_image_strength: 0
  init_noise_correlation: 0
  lora_alpha: 1
  motion_module: models/Motion_Module/mm_sd_v15_v2.ckpt
  path: models/DreamShaper_8_pruned.safetensors
  n_prompt:
  - "blurry, dof"
  prompt:
  - 'a man in the water, in illustrated style, anime, soft lighting, beautiful painting, glowing, painterly strokes'
  seed:
  - 1337
  steps: 35